apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-api
  labels:
    app: birthday-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birthday-api
  template:
    metadata:
      labels:
        app: birthday-api
    spec:
      containers:
        - name: birthday-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: birthday-api-db-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: birthday-api-db-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: birthday-api-db-config
                  key: DB_PASS
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
