apiVersion: v1
kind: Secrets
metadata:
  name: birthday-api-db-config
  labels:
    app: birthday-api
data:
  DB_HOST:
    {{ .Values.db.host | b64enc }}
  DB_USER:
    {{ .Values.db.user | b64enc }}
  DB_PASS:
    {{ .Values.db.password | b64enc }}
  DB_NAME:
    {{ .Values.db.name | b64enc }}
