name: Run tests for birthday-api code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services with docker-compose
        run: docker compose -f docker-compose.yaml build

      - name: Start services with docker-compose
        run: docker compose -f docker-compose.yaml up -d

      - name: Run tester build
        run: docker build . --env DB_HOST=127.0.0.1 --network host --target=tester

      - name: Shutdown services
        if: always()
        run: docker compose -f docker-compose.yaml down
